#!/usr/bin/env bash 
# my herbstluftwm config

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# keybindings
# remove all existing keybindings
hc keyunbind --all

Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-grave emit_hook goto_last_tag # from lasttag.sh
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn ${TERMINAL:-xterm} # use $TERMINAL with xterm as fallback
hc keybind $Mod-Shift-Return spawn st-float 
hc keybind $Mod-m spawn dmenu_run
hc keybind $Mod-Shift-m spawn herbstcommander.sh

# focusing clients
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-b       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

# tags
#tag_names=( {1..9} )
tag_names=( "." "</>" "main" "virt" "v" "vi" "eyez" "viii" "irc" )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-Shift-f floating toggle
hc keybind $Mod-f set_attr clients.focus.floating toggle
hc keybind $Mod-p pseudotile toggle
hc keybind $Mod-w fullscreen toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc attr theme.floating.reset 1
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc rule class=eyez floating=on tag=eyez
hc rule instance=weechat tag=irc 
hc rule instance=nvim-float floating=on 
hc rule instance=st-float floating=on 
hc rule class=mpv floating=on 
hc rule class=Transmission-gtk floating=on
hc rule class=Zathura floating=on
#hc rule role=Dialog floating=on
#hc rule instance=Places floating=on tag=2 
#hc rule instance=voidwire floating=on 
#hc rule instance=lf floating=on 
#hc rule instance=qtfm-float floating=on 

# main layout
hc load main '(split vertical:0.2:1 (split horizontal:0.55:0 (clients vertical:0) (clients vertical:0)) (split horizontal:0.45:0 (split vertical:0.45:0 (clients grid:0) (clients grid:0)) (clients vertical:0)))'
hc rule class=Firefox tag=main index=11
hc rule class=qtfm tag=main index=000
hc rule class=newsboat tag=main index=01

# virt layout
hc load virt '(split horizontal:0.2:1 (clients vertical:0) (split vertical:0.8:1 (clients vertical:0) (clients vertical:0)))' 
hc rule class=Virt-manager tag=virt index=01 pseudotile=on

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# ---- theme styling being ---- # 
## general theme and windows
hc attr theme.active.color '#CEAF51' 
hc attr theme.normal.color '#90ADC6' 
hc attr theme.urgent.color orange
hc attr theme.border_width 2
hc attr theme.floating.border_width 5
hc attr theme.floating.outer_width 1
hc set window_gap 2 

## frames 
hc set frame_bg_transparent 1
hc set frame_border_normal_color black
hc set frame_bg_active_color '#E9EAEC'
hc set frame_bg_normal_color '#333652'
hc set frame_normal_opacity 25
hc set frame_active_opacity 25
hc set frame_padding 2
hc set frame_gap 5
hc set frame_border_width 0
hc set frame_border_inner_width 0

hc set snap_distance 15
# ---- theme styling end ---- # 


# ---- monitors ---- # 
hc detect_monitors
#hc set_monitors 1366x768+0+0 1920x1080+1366+0

## autostart ##
sxhkd &
feh --bg-scale ~/.backgrounds/sprite_shrine_by_justin_totemical.jpg
#feh --bg-scale ~/.local/backgrounds/the_raven_by_mugwort.jpg
#picom -CG -b --experimental-backends --xrender-sync-fence 


# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done

